### ISSUE TITLE
Missing grouped element label

### ISSUE THREAD

**Issue by hayesleigh** [RDFBones/RDFBonesPhaleron#90] opened 2023-04-13 14:25 UTC
**In what module does the bug occur?**
Skeletal paleopathology
 
**Describe the bug**
Within the skeletal paleopathology module the ROI "entire proximal toe phalanx" is not showing up as an option. I double-checked the skeletal inventory where I noticed the bug individual (IX_872) and proximal foot phalanges are present, so the ROI should show up. 

**To Reproduce**
1. Go to Osteo pathology section for individual IX_872-----this error also occurs in the other pathology types (bone addition etc)
2. Click on leg/foot section.
3. Scroll down to the osteoarthritis/osteoporosis section and click on prox toe phalanx test.
4. See error: no ROI option for entire proximal toe phalanx. 

**Expected behavior**
Need to add the ROI of entire proximal toe phalanx. 

**Screenshots**

![image](https://user-images.githubusercontent.com/90316213/231790162-86f0723f-9d16-45ba-ae2b-a847b050bd4a.png)

**Additional context**

**Comment by cuboideum** [comment] 2023-09-07 12:59
I assume that adding the ROIs in question to the ROI groups defining tab affinity will solve the issue.

**Comment by cuboideum** [comment] 2023-09-07 13:01
This seems to be a duplicate of issue #52.

**Comment by cuboideum** [comment] 2023-11-20 12:43
I have checked the example given in the issue in detail. For individual IX_872 the information from the skeletal inventory is as follows:

- Fragments of left proximal foot phalanges: 5
- Fragments of left intermediate foot phalanges: 0
- Fragments of left distal foot phalanges: 0
- Fragments of right proximal foot phalanges: 5
- Fragments of right intermediate foot phalanges: 0
- Fragments of right distal foot phalanges: 0
- Unsided fragments of proximal foot phalanges: 0
- Unsided fragments of intermediate foot phalanges: 4
- Unsided fragments of distal foot phalanges: 2

So, for the OA/OP section, we would expect the following selection:

- Entire left proximal phalanx of toe
- Entire right proximal phalanx of toe
- Entire intermediate phalanx of toe
- Entire distal phalanx of toe

However, we only get to choose from 'Entire intermediate phalanx of toe' and 'Entire distal phalanx of toe'.

Behind the scenes of AnthroGraph, what ROIs are on selection in the Paleopathology module is determined by 'Anatomical regions of interest groups'. The group for the lower limb references 'Entire proximal phalanx of toe' but not 'Entire left proximal phalanx of toe' and 'Entire right proximal phalanx of toe'. This could be a reason why the latter two are not displayed. The former we would not even expect, because the skeletal inventory does not list unsided proximal phalanx fragments.

**Comment by cuboideum** [comment] 2023-12-07 20:56
The remaining implementation in AnthroGraph is covered by issue https://github.com/AnthroGraph/PBP-App/issues/70.

**Comment by cuboideum** [comment] 2023-12-12 12:40
Even after implementation in AnthroGraph, the required ROIs cannot be selected.

This should  be because of the missing implementation of ROI verification.

**Comment by cuboideum** [comment] 2023-12-13 14:05
https://github.com/AnthroGraph/Phaleron-AppOntology/pull/45 added six new ROIs to the 'Phaleron lower limb regions of interest group'. The 'Osteoarthritis and osteoporosis data set section', however, is about the instance of the 'Phaleron lower limb articular regions of interest group'. As phalanges have articular surfaces, they need to be also added to this group.

**Comment by cuboideum** [comment] 2023-12-14 08:45
Fixed with commit https://github.com/AnthroGraph/Phaleron-AppOntology/commit/84976278dd326bfeb658e9561c9ed4d7664f5749.

**Comment by cuboideum** [comment] 2023-12-15 11:00
The issue is resolved, the required ROIs can now be selected in the AnthroGraph production instance.

**Closed as completed by cuboideum** 2023-12-15 11:00 UTC
Labels: bug, palaeopathology module
